### ISSUE TITLE
document implemented XPath version

### ISSUE THREAD

**Issue by funkyfuture** [RazrFalcon/choose-your-xml-rs#3]
this helpful reference would be even more helpful if the implemented XPath version of a library would be noted. the same would apply for XQuery if there was any support of that.

**Comment by RazrFalcon** [comment]
The table contains XPath and XQuery. Can you clarify your question?

**Comment by funkyfuture** [comment]
[there are](https://www.w3.org/standards/techs/xpath) different versions of XPath and XQuery with quiet different extents and semnatical differences. hence it would be desirable wot know which library implements which of these.

**Comment by RazrFalcon** [comment]
I see. Looks like `sxd-xpath` supports only `XPath 1.0`.  Will add this to the table, as a note, since there is only one implementation now.
